//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HueDesktop.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HueDesktop.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/json.
        /// </summary>
        internal static string BODY_TYPE_JSON {
            get {
                return ResourceManager.GetString("BODY_TYPE_JSON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description:.
        /// </summary>
        internal static string BRIDGE_DESC {
            get {
                return ResourceManager.GetString("BRIDGE_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manufacturer:.
        /// </summary>
        internal static string BRIDGE_MANUF {
            get {
                return ResourceManager.GetString("BRIDGE_MANUF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manufacturer URL:.
        /// </summary>
        internal static string BRIDGE_MANUF__URL {
            get {
                return ResourceManager.GetString("BRIDGE_MANUF__URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model Number:.
        /// </summary>
        internal static string BRIDGE_MNUM {
            get {
                return ResourceManager.GetString("BRIDGE_MNUM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model Name:.
        /// </summary>
        internal static string BRIDGE_NAME {
            get {
                return ResourceManager.GetString("BRIDGE_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serial Number:.
        /// </summary>
        internal static string BRIDGE_SNUM {
            get {
                return ResourceManager.GetString("BRIDGE_SNUM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP Address:.
        /// </summary>
        internal static string BRIDGE_URL {
            get {
                return ResourceManager.GetString("BRIDGE_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version Number:.
        /// </summary>
        internal static string BRIDGE_VERSION {
            get {
                return ResourceManager.GetString("BRIDGE_VERSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hueBridgeDescription.xml.
        /// </summary>
        internal static string BRIDGE_XML {
            get {
                return ResourceManager.GetString("BRIDGE_XML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hueBridgeDescriptionAbridged.xml.
        /// </summary>
        internal static string BRIDGE_XML1 {
            get {
                return ResourceManager.GetString("BRIDGE_XML1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn OFF.
        /// </summary>
        internal static string BTNTXT_OFF {
            get {
                return ResourceManager.GetString("BTNTXT_OFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn ON.
        /// </summary>
        internal static string BTNTXT_ON {
            get {
                return ResourceManager.GetString("BTNTXT_ON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bulb {
            get {
                object obj = ResourceManager.GetObject("bulb", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading file - Description.xml --&gt; {0}% Done..
        /// </summary>
        internal static string DOWNLD_FILE_STR {
            get {
                return ResourceManager.GetString("DOWNLD_FILE_STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Hue Bridges found! Please check if you are connected to the same network..
        /// </summary>
        internal static string ERROR00 {
            get {
                return ResourceManager.GetString("ERROR00", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not look for bridges! Network issue,.
        /// </summary>
        internal static string ERROR01 {
            get {
                return ResourceManager.GetString("ERROR01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please press the button on your Hue bridge before clicking the &quot;CONNECT&quot; button..
        /// </summary>
        internal static string ERROR02 {
            get {
                return ResourceManager.GetString("ERROR02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No lights paired with the Bridge! Try pressing the button on the bridge and click &apos;CONNECT button again.
        /// </summary>
        internal static string ERROR03 {
            get {
                return ResourceManager.GetString("ERROR03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check if your PC is connected to the same network as the bridge.
        /// </summary>
        internal static string ERROR05 {
            get {
                return ResourceManager.GetString("ERROR05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter subnet mask (between 1 to 255) in the numeric text box on left..
        /// </summary>
        internal static string ERROR07 {
            get {
                return ResourceManager.GetString("ERROR07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error sending name details to the bridge..
        /// </summary>
        internal static string ERROR4 {
            get {
                return ResourceManager.GetString("ERROR4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap helper_icon {
            get {
                object obj = ResourceManager.GetObject("helper_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ipadd.
        /// </summary>
        internal static string IP_ADDRESS_FILE {
            get {
                return ResourceManager.GetString("IP_ADDRESS_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to myhue.
        /// </summary>
        internal static string KEY_FILE {
            get {
                return ResourceManager.GetString("KEY_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to connect to the remote server.
        /// </summary>
        internal static string LAN_DOWN {
            get {
                return ResourceManager.GetString("LAN_DOWN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is a {1}. It is currently {2}. Click on the light icon to set the color of this light..
        /// </summary>
        internal static string LIGHT_DETAILS {
            get {
                return ResourceManager.GetString("LIGHT_DETAILS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap lightstrip {
            get {
                object obj = ResourceManager.GetObject("lightstrip", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAX.
        /// </summary>
        internal static string TEXT_MAX {
            get {
                return ResourceManager.GetString("TEXT_MAX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OFF.
        /// </summary>
        internal static string TEXT_OFF {
            get {
                return ResourceManager.GetString("TEXT_OFF", resourceCulture);
            }
        }
    }
}
